<?php render_component('page-hero', ['asset' => $pageHeroAssets['contact'], 'breadcrumbs' => $breadcrumbs, 'interior' => $interior, 'locale' => $locale]); ?>

<section class="contact-section section"><div class="shell contact-layout">
    <div class="contact-details" data-reveal><p class="kicker"><?= e($home['footer']['contact']) ?></p><h2><?= e($locale === 'tr' ? 'Doğrudan iletişim' : 'Direct contact') ?></h2><address><a href="mailto:<?= e($site['contact']['email']) ?>"><?= e($site['contact']['email']) ?></a><a href="tel:<?= e($site['contact']['phoneHref']) ?>"><?= e($site['contact']['phone']) ?></a><a href="tel:<?= e($site['contact']['secondaryPhoneHref']) ?>"><?= e($site['contact']['secondaryPhone']) ?></a></address><dl><div><dt><?= e($home['footer']['office']) ?></dt><dd><?= e($site['contact']['officeAddress']) ?></dd></div><div><dt><?= e($home['footer']['factory']) ?></dt><dd><?= e($site['contact']['factoryAddress']) ?></dd></div><div><dt><?= e($locale === 'tr' ? 'Çalışma saatleri' : 'Working hours') ?></dt><dd><?= e($site['contact']['hours'][$locale]) ?></dd></div></dl><div class="social-links"><?php foreach ($site['contact']['social'] as $social): ?><a href="<?= e(safe_href($social['url'])) ?>" target="_blank" rel="noopener"><?= e($social['label']) ?><span aria-hidden="true">↗</span></a><?php endforeach; ?></div></div>
    <div class="quote-form-wrap" id="quote-form" data-reveal><p class="kicker"><?= e($interior['eyebrow']) ?></p><h2><?= e($interior['formTitle']) ?></h2><p><?= e($interior['formIntro']) ?></p><div class="form-notice" role="status"><?= e($locale === 'tr' ? 'Local geliştirme modu: form verileri gönderilmez.' : 'Local development mode: form data is not submitted.') ?></div>
        <?php render_component('contact-form', ['contract' => $formContract, 'locale' => $locale, 'interior' => $interior]); ?>
    </div>
</div></section>

<section class="map-section"><div class="shell"><div class="map-section__heading"><p class="kicker"><?= e($interior['mapTitle']) ?></p><h2><?= e($locale === 'tr' ? 'İstanbul’daki merkez ve üretim tesisi' : 'Head office and production facility in Istanbul') ?></h2></div><div class="map-section__locations"><a href="<?= e('https://www.google.com/maps/search/?api=1&query=' . rawurlencode($site['contact']['officeAddress'])) ?>" target="_blank" rel="noopener"><span>01</span><strong><?= e($home['footer']['office']) ?></strong><small><?= e($site['contact']['officeAddress']) ?></small></a><a href="<?= e('https://www.google.com/maps/search/?api=1&query=' . rawurlencode($site['contact']['factoryAddress'])) ?>" target="_blank" rel="noopener"><span>02</span><strong><?= e($home['footer']['factory']) ?></strong><small><?= e($site['contact']['factoryAddress']) ?></small></a></div></div></section>
